---
apiVersion: v1
kind: Secret
metadata:
  name: hamburg-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-test/hamburg-frontend-gitops
